### ISSUE TITLE
ERROR: Build Path

### ISSUE THREAD

**Issue by sheperdsonbrown** [diging/giles-eco-docker#2]
docker-compose.yml needs to be updated for andromeda build path. It is currently lower-case, but needs to be changed to uppercase Andromeda.

andromeda:
        build: ./Andromeda
        ports:

Error if not updated : (command and result below)
alexander@sheperdsonbrown:/home/giles-eco-docker/latest_tag/Andromeda$ sudo docker-compose up
ERROR: build path /home/giles-eco-docker/latest_tag/andromeda either does not exist, is not accessible, or is not a valid URL.

**Comment by jdamerow** [comment]
Interesting, that doesn't seem to be a problem with Docker on Mac. It's fixed in the next commit.
