### ISSUE TITLE
Is there a newer Docker file ?

### ISSUE THREAD

**Issue by sdeusch** [diging/giles-eco-docker#3]
oracle-java8-installer not working 
GPG fails

**Comment by jdamerow** [comment]
I'll take a look at this next week!

**Comment by jdamerow** [comment]
I've updated the docker files, it should work now.

**Comment by jdamerow** [comment]
Latest tag: e6d66a4064bdc1fee23cda8a74ebe3a359afd595
Develop: 0075b50b5909ee43408f62f1c0becaee88c0900e
